cat ./arch/.gitignore
cat ./block/.gitignore
cat ./certs/.gitignore
cat ./crypto/.gitignore
cat ./Documentation/.gitignore
cat ./drivers/.gitignore
cat ./firmware/.gitignore
cat ./fs/.gitignore
cat ./include/.gitignore
cat ./init/.gitignore
cat ./ipc/.gitignore
cat ./kernel/.gitignore
cat ./lib/.gitignore
cat ./litmus/.gitignore
cat ./mm/.gitignore
cat ./net/.gitignore
cat ./samples/.gitignore
cat ./scripts/.gitignore
cat ./security/.gitignore
cat ./sound/.gitignore
cat ./tools/.gitignore
cat ./usr/.gitignore
cat ./virt/.gitignore

